version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jobsdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

